  // <auto-generated />
using System;
using AutoCompare_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoCompare_API.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AutoCompare_API.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("AutoCompare_API.Models.MasterService", b =>
                {
                    b.Property<int>("masterServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("masterServiceId"));

                    b.Property<bool>("active")
                        .HasColumnType("bit");

                    b.Property<string>("category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("serviceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("masterServiceId");

                    b.ToTable("master_services");

                    b.HasData(
                        new
                        {
                            masterServiceId = 1,
                            active = false,
                            category = "",
                            icon = "",
                            name = "Oil Change",
                            serviceType = ""
                        },
                        new
                        {
                            masterServiceId = 2,
                            active = false,
                            category = "",
                            icon = "",
                            name = "Filter Change",
                            serviceType = ""
                        },
                        new
                        {
                            masterServiceId = 3,
                            active = false,
                            category = "",
                            icon = "",
                            name = "Fluid Exchange",
                            serviceType = ""
                        },
                        new
                        {
                            masterServiceId = 4,
                            active = false,
                            category = "",
                            icon = "",
                            name = "Tire Services",
                            serviceType = ""
                        },
                        new
                        {
                            masterServiceId = 5,
                            active = false,
                            category = "",
                            icon = "",
                            name = "Filter Replacement",
                            serviceType = ""
                        },
                        new
                        {
                            masterServiceId = 6,
                            active = false,
                            category = "",
                            icon = "",
                            name = "Battery Testing & Replacement",
                            serviceType = ""
                        });
                });

            modelBuilder.Entity("AutoCompare_API.Models.Shop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("bit");

                    b.Property<double>("Lat")
                        .HasColumnType("float");

                    b.Property<double>("Lng")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkHours")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("shops");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "1245 Pembina Highway",
                            Bio = "Fast oil changes, tire rotations, and seasonal tire swaps for all makes and models.",
                            Category = "Oil Change & Tires",
                            City = "Winnipeg",
                            CreatedAt = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "info@quicklubetire.ca",
                            IsOpen = true,
                            Lat = 49.807400000000001,
                            Lng = -97.153199999999998,
                            Name = "Quick Lube & Tire Centre",
                            Phone = "204-555-0101",
                            PostalCode = "R3T 2C1",
                            Province = "MB",
                            WorkHours = "Mon-Fri 7:00-19:00, Sat 8:00-17:00"
                        },
                        new
                        {
                            Id = 2,
                            Address = "88 Portage Avenue",
                            Bio = "Full-service auto repair including engine diagnostics, suspension work, and scheduled maintenance.",
                            Category = "General Repair",
                            City = "Winnipeg",
                            CreatedAt = new DateTime(2025, 2, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "service@precisionauto.ca",
                            IsOpen = true,
                            Lat = 49.895099999999999,
                            Lng = -97.138400000000004,
                            Name = "Precision Auto Mechanics",
                            Phone = "204-555-0142",
                            PostalCode = "R3T 2C1",
                            Province = "MB",
                            WorkHours = "Mon-Sat 8:00-18:00"
                        },
                        new
                        {
                            Id = 3,
                            Address = "502 St. Mary's Road",
                            Bio = "Specialists in brake pads, rotors, calipers, and precision wheel alignment.",
                            Category = "Brakes & Alignment",
                            City = "Winnipeg",
                            CreatedAt = new DateTime(2025, 2, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "bookings@expressbrake.ca",
                            IsOpen = true,
                            Lat = 49.828299999999999,
                            Lng = -97.110500000000002,
                            Name = "Express Brake & Alignment",
                            Phone = "204-555-0198",
                            PostalCode = "R3T 2C1",
                            Province = "MB",
                            WorkHours = "Mon-Fri 8:00-17:30"
                        },
                        new
                        {
                            Id = 4,
                            Address = "3100 Regent Avenue West",
                            Bio = "Transmission rebuilds, clutch repair, and drivetrain diagnostics for domestic and import vehicles.",
                            Category = "Transmission",
                            City = "Winnipeg",
                            CreatedAt = new DateTime(2025, 3, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "repairs@metrotrans.ca",
                            IsOpen = true,
                            Lat = 49.895800000000001,
                            Lng = -97.015600000000006,
                            Name = "Metro Transmission Specialists",
                            Phone = "204-555-0167",
                            PostalCode = "R3T 2C1",
                            Province = "MB",
                            WorkHours = "Mon-Fri 7:30-18:00"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Mobile — Greater Winnipeg Area",
                            Bio = "On-site battery boosts, flat tire changes, minor repairs, and emergency roadside assistance.",
                            Category = "Mobile Service",
                            City = "Winnipeg",
                            CreatedAt = new DateTime(2025, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "dispatch@roadsidemobile.ca",
                            IsOpen = true,
                            Lat = 49.884700000000002,
                            Lng = -97.187600000000003,
                            Name = "Roadside Mobile Repair Co.",
                            Phone = "204-555-0133",
                            PostalCode = "R3T 2C1",
                            Province = "MB",
                            WorkHours = "Daily 6:00-22:00"
                        });
                });

            modelBuilder.Entity("AutoCompare_API.Models.ShopService", b =>
                {
                    b.Property<int>("shopServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("shopServiceId"));

                    b.Property<bool>("active")
                        .HasColumnType("bit");

                    b.Property<int>("durationMin")
                        .HasColumnType("int");

                    b.Property<int>("etaMin")
                        .HasColumnType("int");

                    b.Property<bool>("isAtShop")
                        .HasColumnType("bit");

                    b.Property<bool>("isMobile")
                        .HasColumnType("bit");

                    b.Property<bool>("isRoadside")
                        .HasColumnType("bit");

                    b.Property<int>("masterServiceId")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("price")
                        .HasColumnType("float");

                    b.Property<string>("priceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("shopId")
                        .HasColumnType("int");

                    b.Property<int>("sortOrder")
                        .HasColumnType("int");

                    b.HasKey("shopServiceId");

                    b.HasIndex("masterServiceId");

                    b.HasIndex("shopId");

                    b.ToTable("shop_services");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AutoCompare_API.Models.Shop", b =>
                {
                    b.HasOne("AutoCompare_API.Models.ApplicationUser", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("AutoCompare_API.Models.ShopService", b =>
                {
                    b.HasOne("AutoCompare_API.Models.MasterService", "MasterService")
                        .WithMany("shopServices")
                        .HasForeignKey("masterServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AutoCompare_API.Models.Shop", "Shop")
                        .WithMany()
                        .HasForeignKey("shopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MasterService");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("AutoCompare_API.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("AutoCompare_API.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoCompare_API.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("AutoCompare_API.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AutoCompare_API.Models.MasterService", b =>
                {
                    b.Navigation("shopServices");
                });
#pragma warning restore 612, 618
        }
    }
}
